apiVersion: v1
kind: Service
metadata:
  name: {{.Values.appName}}-svc
spec:
  type: ClusterIP
  selector:
    app: {{.Values.appName}}-pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{.Values.bePort | default 80}}