apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: taa
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: taa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
      namespace: taa
    spec:
      containers:
      - name: mysql-db
        image: mysql:5.6
        volumeMounts:
        - name:  mysql-volume
          mountPath:  /var/lib/mysql
        ports:
        - containerPort:  3306
          protocol: TCP
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: taa-cfm          
              key: db_pass
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: taa-cfm          
              key: db_name
      volumes:
      - name: mysql-volume
        persistentVolumeClaim:
          claimName: mysql-pv-claim
--- 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: taa
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
--- 
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/db"
--- 
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: manual
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer