apiVersion: v1
kind: Pod
metadata:
  name: previous-app
  labels:
    app: codestar-app
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: 512Mi
        cpu: "0.5"
      requests:
        memory: 256Mi
        cpu: "0.2"