apiVersion: v1
kind: Namespace
metadata:
    name: {{ .Release.Name }}-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: {{.Values.appName}}-configmap
    namespace: {{ .Release.Name }}-ns
data:
    codestarAppVer: v1
    lastUpdate: {{.Values.lastUpdate}}
