apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-demo
data:
  key1: "value1"
  db_host: "localhost"
  db_user: "admin"
  db_password: "12345678"
  db_name: "mydb"
  multivalue: >
    port=3306
    mail=gmail
    key1=value1
    key2=value2

---
apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo 
      image: alpine
      command: ["sleep", "3600"]
      resources:
        limits:
          memory: 512Mi
          cpu: "0.5"
        requests:
          memory: 256Mi
          cpu: "0.2"
      env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: configmap-demo           # The ConfigMap this value comes from.
              key: db_host                   # The key to fetch.
      volumeMounts:
      - name: config-from-cm
        mountPath: "/config"
        readOnly: true
  volumes:
    - name: config-from-cm
      configMap:
        name: configmap-demo
        items:
        - key: "db_host"
          path: "db_host"
        - key: "multivalue"
          path: "multivalue"

