apiVersion: apps/v1
kind: Deployment
metadata:
  name: codestar-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
        ports:
        - containerPort: 80
      tolerations:
      - key: "fe"
        operator: "Equal"
        value: "notnginx"
        effect: "NoSchedule"