apiVersion: apps/v1
kind: Deployment
metadata:
  name: codestar-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
        ports:
        - containerPort: 80
      tolerations:
      - key: "be"
        operator: "Equal"
        value: "notnginx"
        effect: "NoExecute"
        tolerationSeconds: 3600 # This config will set time before evicted