apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mycluster
  region: ap-southeast-1

nodeGroups:
  - name: node-group-1
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 8
    ssh:
      allow: true # will use ~/.ssh/id_rsa.pub as the default ssh key
  - name: node-group-2
    instanceType: t2.micro
    desiredCapacity: 1
    volumeSize: 8
    ssh:
      allow: true
      